title: confidentidiots.com
email: confidentidiots@uys.io
description: >- # this means to ignore newlines until "baseurl:"
  An indie-vidual games dev.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://confidentidiots.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: confidiot
github_username:  confidentidiots
disqus: confidentidiots
google_analytics: UA-114645042-1
# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
plugins:
  - jekyll-feed
collections:
  contumacious:
    output: true
    permalink: /:collection/:path
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
